# Enforce HTTPS + canonical www and set HSTS
[[redirects]]
  from = "http://nordestinopizzariadelivery.com.br/*"
  to = "https://www.nordestinopizzariadelivery.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://nordestinopizzariadelivery.com.br/*"
  to = "https://www.nordestinopizzariadelivery.com.br/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
